"""create vocabulary table

Revision ID: 8b9521b77772
Revises: 10c8c4b5819b
Create Date: 2026-04-19 13:39:25.139195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9521b77772'
down_revision: Union[str, None] = '10c8c4b5819b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('japanese', sa.String(length=64), nullable=False),
    sa.Column('kana', sa.String(length=64), nullable=False),
    sa.Column('accent', sa.SmallInteger(), nullable=True),
    sa.Column('chinese', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_id'), 'vocabulary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_id'), table_name='vocabulary')
    op.drop_table('vocabulary')
    # ### end Alembic commands ###
